version: '3.3'

services:
  db:
    container_name: gabriel-waltman-db
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'gabriel-waltman'
      MYSQL_PASSWORD: 'gabriel-waltman-db'
      MYSQL_ROOT_PASSWORD: 'gabriel-waltman-db'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
