name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "NEXT_PUBLIC_BACKEND_BASE_URL=${{ secrets.NEXT_PUBLIC_BACKEND_BASE_URL }}" > .env && echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: sudo docker build -t gabrielwaltmann/waltmann_client:latest .

      - name: Push docker image
        run: sudo docker push gabrielwaltmann/waltmann_client

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete old docker images
        run: docker system prune -a -f

      - name: Pull docker image
        run: sudo docker pull gabrielwaltmann/waltmann_client:latest

      - name: Remove old container if exists
        run: sudo docker rm -f waltmann_client

      - name: Run docker container
        run: docker run -d -p 3000:3000 -e PORT='${{ secrets.PORT }}' -e NEXT_PUBLIC_BACKEND_BASE_URL='${{ secrets.NEXT_PUBLIC_BACKEND_BASE_URL }}' --name waltmann_client gabrielwaltmann/waltmann_client:latest
