name: Build with next, push to docker hub and deploy at VPS

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    name: Build with next, push to docker hub and deploy at VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "NEXT_PUBLIC_BACKEND_BASE_URL=${{ secrets.NEXT_PUBLIC_BACKEND_BASE_URL }}" > .env && echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: sudo docker build -t gabrielwaltmann/waltmann_client:latest -f ./docker/Dockerfile.prod .

      - name: Push docker image
        run: sudo docker push gabrielwaltmann/waltmann_client

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            cd ~/gabrielwaltmann
            docker-compose pull waltmann-frontend
            docker compose down waltmann-frontend
            docker compose up -d --no-deps waltmann-frontend
